name: Automatic Documentation for Launcher

on:
  pull_request:

jobs:
  update_docs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install Launcher
      env:
        BRANCH: ${{ github.head_ref }}
      id: install-launcher
      run: cargo install --git https://github.com/${{ github.repository }} --branch "$BRANCH" text-generation-launcher
    
    - name: Check launcher Docs are up-to-date
      run: |
        echo text-generation-launcher --help
        python update_doc.py --check
